services:
  - type: web
    name: ultravioleta-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 10000 